In [1]:
#initial imports that you may find useful
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
import numpy as np

In [2]:
#additional imports
import pandas as pd


For this assignment you will need to use the sklearn framework to implement a custom Naive Bayes classifier.  The classifier only needs to handle binary data (both the attributes and the classes).  The attributes will always have a value of 0 or 1.  The class labels will always have a value of 1 or -1.  You can use libraries to help with the data processing, calculations, etc, but you must implement your own Naïve Bayes algorithm.  Do not use an existing implementation.  One important implementation detail is that you should convert the probabilities to log probabilities to avoid the number becoming to small to represent as a floating point number.  For example instead of computing P(x|c)P(c) compute log(P(x|c)+log(P(c)). Provide your implementation below.

In [20]:

# #Your Naive Bayes Implementation goes here.
# #Adjust this as you see fit

class BinaryNBClassifier(BaseEstimator, ClassifierMixin):        
    def __init__(self, k=0.5):
        self.k = k
        self.word_probs = []

    def count_universe(self, X): #Rob: Python lesson learned... when you call using self, you have to accept self as a parameter
        event_count, feature_count = X.shape

        # Count values per column. This requires transposing the array (from columns to row)
        for col in X.T:
            print(col)
            unique, counts = np.unique(X_train, return_counts=True)
            dict(zip(unique, counts)) 
            print(f"Unique values: {unique}  Count: {counts}")


        return event_count, feature_count

    def word_probabilities(counts, total_spams, total_non_spams, k=0.5):
        """turn the word_counts into a list of triplets
        w, p(w | spam) and p(w | ~spam)"""
        
        return [(w,
                (spam + k) / (total_spams + 2 * k),
                (non_spam + k) / (total_non_spams + 2 * k))
                for w, (spam, non_spam) in counts.iteritems()]

    def fit(self, X, y):
        event_count, feature_count = self.count_universe(X)
        print(f"event_count: {event_count} feature_count: {feature_count}")
        return self


Resources Consulted:
* https://sklearn-template.readthedocs.io/en/latest/user_guide.html
* https://saturncloud.io/blog/how-to-keep-column-names-when-converting-from-pandas-to-numpy
* https://github.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/blob/master/Naiye%20Bayes%20classification%20application.ipynb

In [4]:
df = pd.read_csv('Datasets for Assignment 2/test1_1.csv',)
df.info

<bound method DataFrame.info of    0  1  2  3  4  5  6  7  8  9  Class
0  1  0  0  0  1  1  0  1  1  1      1
1  1  1  1  1  0  1  0  1  0  1      1
2  0  1  0  0  1  1  1  1  0  1      1
3  1  1  0  0  0  1  1  0  1  1      1
4  0  0  0  1  0  1  1  0  0  1      1
5  1  0  1  1  0  1  0  1  1  1     -1
6  0  0  0  1  0  1  1  1  1  1     -1
7  1  0  1  0  1  0  0  1  0  0     -1
8  1  0  0  1  1  0  0  0  0  1     -1
9  1  0  1  0  0  0  0  0  0  1     -1>

In [5]:
#Spliting the dataset in independent and dependent variables
X = df.iloc[:,:-1].values # The idea here is to capture all the columns except the last one as X
y = df['Class'].values



In [6]:
X
X.shape
a, b = X.shape
print(a)

10


In [7]:
y

array([ 1,  1,  1,  1,  1, -1, -1, -1, -1, -1])

In [8]:
# Splitting the dataset into the Training set and Test set
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1.0, random_state = 42)

# For this particular exercise, the instruction is to use all the samples for training and testing

X_train = X
X_test = X
y_train = y
y_test = y


In [19]:
unique, counts = np.unique(X_train, return_counts=True)
dict(zip(unique, counts))

{0: 47, 1: 53}

In [25]:
arr2 = np.split(X_train, 1, axis=1)  
arr2

[array([[1, 0, 0, 0, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 0, 1, 0, 1],
        [0, 1, 0, 0, 1, 1, 1, 1, 0, 1],
        [1, 1, 0, 0, 0, 1, 1, 0, 1, 1],
        [0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        [1, 0, 1, 1, 0, 1, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
        [1, 0, 0, 1, 1, 0, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 1]])]

In [21]:
NBClassifier = BinaryNBClassifier()
NBClassifier.fit(X_train, y_train)

[1 1 0 1 0 1 0 1 1 1]
Unique values: [0 1]  Count: [47 53]
[0 1 1 1 0 0 0 0 0 0]
Unique values: [0 1]  Count: [47 53]
[0 1 0 0 0 1 0 1 0 1]
Unique values: [0 1]  Count: [47 53]
[0 1 0 0 1 1 1 0 1 0]
Unique values: [0 1]  Count: [47 53]
[1 0 1 0 0 0 0 1 1 0]
Unique values: [0 1]  Count: [47 53]
[1 1 1 1 1 1 1 0 0 0]
Unique values: [0 1]  Count: [47 53]
[0 0 1 1 1 0 1 0 0 0]
Unique values: [0 1]  Count: [47 53]
[1 1 1 0 0 1 1 1 0 0]
Unique values: [0 1]  Count: [47 53]
[1 0 0 1 0 1 1 0 0 0]
Unique values: [0 1]  Count: [47 53]
[1 1 1 1 1 1 1 0 1 1]
Unique values: [0 1]  Count: [47 53]
event_count: 10 feature_count: 10


BinaryNBClassifier()

In [ ]:
#Train and test your BinaryNBClassifier and the sklearn CategoricalNBClassifier on the datasets from canvas
from sklearn.naive_bayes import CategoricalNB
cclassifier = CategoricalNB()
cclassifier.fit(X_train, y_train)

In [ ]:
# Predicting the set results
y_pred = cclassifier.predict(X_train)
print(y_pred)

In [ ]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_train,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:]

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
print(cm)

In [ ]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Categorical Clasification is: ', corrPred/(cm.sum()))   

Now you will train and test your Binary Naive Bayes classifier on a few different datasets.  The datasets can be downloaded from canvas.  They are linked in the assignment description.  For this part of the assignment we will not be splitting the data into training, validation and test data sets.  Instead you should use the entire dataset for training and the entire dataset for testing.  You will need to complete the following table (you can just output the results in this format you don't need to copy them into the text field).

|dataset|# of instances|# of features | Your NB Training Time | Your NB Test Time | Your NB Accuracy | sklearn CategoricalNB Training Time | sklearn Categorical NB Test Time | sklearn CategoricalNB Accuracy|
|-----------|------------|-------------|------------------|-------------------|-------------------------|---------------------------------|------------------------|----------------------------------|
test1_1 |
test1_2 |
test1_4 |
test1_5 |
test2_1 |
test2_2 |
test2_4 |
test2_5 |
test4_1 |
test4_2 |
test4_4 |
test4_5 |
test5_1 |
test5_2 |
test5_4 |


In [ ]:
#Train and test your BinaryNBClassifier and the sklearn CategoricalNBClassifier on the datasets from canvas


The next step for this assignment is split the vote dataset (also found on canvas) into a *train/test split* (use 20% of the data for testing).  Train both algorithms on the training data using *cross-fold validation* and then report the accuracy, f1-score, mcc and informedness results.

In [ ]:
#Split the vote dataset
#Use cross-validatation to compare BinaryNBClassifier against CategoricalNBClassifier

Finally, choose the algorithm that performed the best on the cross-validation, train it on all the training data and test on the test data.  Report the accuracy, f1-score, mcc and informedness results

In [ ]:
#Final Generalization test