Credit to: https://github.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/blob/master/Naiye%20Bayes%20classification%20application.ipynb

In [1]:
import pandas as pd
import numpy as np
import sklearn.naive_bayes


In [13]:
#initial imports that you may find useful
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
import numpy as np

In [ ]:

#Your Naive Bayes Implementation goes here.
#Adjust this as you see fit

class BinaryNBClassifier(BaseEstimator, ClassifierMixin):        
    def __init__(self, k=0.5):
        self.k = k
        self.word_probs = []

    def fit(self, X, y):
        self.classes_ = np.unique(y)
        return self

    def train(self, training_set):

        # count spam and non-spam messages
        num_spams = len([is_spam
                         for message, is_spam in training_set
                         if is_spam])
        num_non_spams = len(training_set) - num_spams

        # run training data through our "pipeline"
        word_counts = count_words(training_set)
        self.word_probs = word_probabilities(word_counts,
                                             num_spams,
                                             num_non_spams,
                                             self.k)

    def classify(self, message):
        return spam_probability(self.word_probs, message)
        
    def predict(self, X):
        return np.random.randint(0, self.classes_.size,
                                 size=X.shape[0])
    
    pass
    
def tokenize(message):
    message = message.lower()                       # convert to lowercase
    all_words = re.findall("[a-z0-9']+", message)   # extract the words
    return set(all_words)                           # remove duplicates


def count_words(training_set):
    """training set consists of pairs (message, is_spam)"""
    counts = defaultdict(lambda: [0, 0])
    for message, is_spam in training_set:
        for word in tokenize(message):
            counts[word][0 if is_spam else 1] += 1
    return counts

def word_probabilities(counts, total_spams, total_non_spams, k=0.5):
    """turn the word_counts into a list of triplets
    w, p(w | spam) and p(w | ~spam)"""
    return [(w,
            (spam + k) / (total_spams + 2 * k),
            (non_spam + k) / (total_non_spams + 2 * k))
            for w, (spam, non_spam) in counts.iteritems()]

def spam_probability(word_probs, message):
    message_words = tokenize(message)
    log_prob_if_spam = log_prob_if_not_spam = 0.0

    # iterate through each word in our vocabulary
    for word, prob_if_spam, prob_if_not_spam in word_probs:

        # if *word* appears in the message,
        # add the log probability of seeing it
        if word in message_words:
            log_prob_if_spam += math.log(prob_if_spam)
            log_prob_if_not_spam += math.log(prob_if_not_spam)

        # if *word* doesn't appear in the message
        # add the log probability of _not_ seeing it
        # which is log(1 - probability of seeing it)
        else:
            log_prob_if_spam += math.log(1.0 - prob_if_spam)
            log_prob_if_not_spam += math.log(1.0 - prob_if_not_spam)

    prob_if_spam = math.exp(log_prob_if_spam)
    prob_if_not_spam = math.exp(log_prob_if_not_spam)
    return prob_if_spam / (prob_if_spam + prob_if_not_spam)



seed = np.random
# random.seed(0)      # just so you get the same answers as me
train_data, test_data = split_data(data, 0.75)

classifier = NaiveBayesClassifier()
classifier.train(train_data)

In [12]:
df = pd.read_csv('Datasets for Assignment 2/test4_2.csv',)
df.info

<bound method DataFrame.info of       0  1  2  3  4  5  6  7  8  9  ...  91  92  93  94  95  96  97  98  99  \
0     1  1  0  0  1  1  1  0  0  0  ...   1   0   1   0   1   1   0   0   1   
1     1  1  1  0  1  0  0  0  1  0  ...   1   0   1   1   1   0   0   0   1   
2     1  1  0  1  1  1  0  1  0  1  ...   1   0   1   1   1   0   0   0   1   
3     0  1  1  1  1  0  0  1  0  0  ...   1   0   1   0   0   1   0   0   1   
4     0  1  0  0  1  0  0  0  1  1  ...   1   0   1   1   1   0   0   0   1   
...  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
9995  0  1  0  0  1  1  0  1  0  0  ...   1   0   1   1   0   1   0   1   1   
9996  1  1  1  1  1  1  0  0  1  0  ...   1   1   0   1   1   0   1   1   1   
9997  0  0  1  0  1  1  1  1  1  1  ...   1   1   1   0   0   1   1   1   0   
9998  1  0  0  0  1  1  0  0  0  0  ...   1   1   0   0   1   1   1   1   1   
9999  0  0  0  0  1  0  0  0  0  0  ...   1   1   0   1   1   1   1   1   1   

      Class  
0    

In [3]:
#Spliting the dataset in independent and dependent variables
X = df.iloc[:,:-1].values # The idea here is to capture all the columns except the last one as X
y = df['Class'].values



In [4]:
X

array([[1, 1, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [5]:
y

array([ 1,  1,  1, ..., -1, -1,  1])

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [7]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import BernoulliNB
nvclassifier = BernoulliNB()
nvclassifier.fit(X_train, y_train)

BernoulliNB()

In [14]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_train)
print(y_pred)

[-1  1  1 ... -1  1 -1]


In [17]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_train,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:]

array([[-1, -1],
       [ 1,  1],
       [ 1,  1],
       ...,
       [-1, -1],
       [ 1,  1],
       [-1, -1]])

In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
print(cm)

[[3821  182]
 [ 191 3806]]


In [20]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))   

Correct predictions:  7627
False predictions 373


Accuracy of the Naive Bayes Clasification is:  0.953375
